### ISSUE TITLE
Migration failed

### ISSUE THREAD

**Issue by SmbatPoghosyan** [Silvanite/novatoolpermissions#47]
SQLSTATE[HY000]: General error: 1005 Can't create table `my_table`.`#sql-dac_bb` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `role_user` add constraint `role_user_user_id_foreign` foreign key (`user_id`) references `users  
  ` (`id`) on delete cascade)

**Comment by SmbatPoghosyan** [comment]
Laravel 5.7

**Comment by wrtisans** [comment]
i've the same error, im using uuid in my users PK, please help...

` SQLSTATE[HY000]: General error: 1005 Can't create table `adm`.`role_user` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL: alter table `role_user` add constraint `role_user_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade)
`

**Comment by m2de** [comment]
Apologies. This is caused by the Laravel 5.8 change in user id to bigInteger. I will try and re-tag a 5.7 release of brandenburg shortly which should resolve this issue.

**Comment by SmbatPoghosyan** [comment]
I'm on 5.7 version. But this issue is actual.

**Comment by m2de** [comment]
Ok. I have pushed up specific brandenburg releases for pre and post 5.8. It should now pull in the correct version based on your installed Laravel version when you install the package or composer update. Please let me know if this doesn't resolve the issue for you and I will re-open. Cheers!

**Comment by GuidoThomassen** [comment]
Hi, I've still got this issue when running `php artisan migrate`. I've tried running `composer update` but this doesn't fix the issue unfortunately. I'm running on Laravel 5.8.18. Any idea on how to resolve this issue?

**Comment by GuidoThomassen** [comment]
Oh I see what I did wrong, my user still had a `increments` instead of `bigIncrements` on the id. No need to re-open issue.
